aws ec2 run-instances --region ap-south-1 --image-id ami-ee5f2981 --count 1 --instance-type c4.large --key-name pdcc_Mumbai --security-groups allow_all
aws ec2 run-instances --region eu-west-2 --image-id ami-e4f4fe80 --count 1 --instance-type c4.large --key-name pdcc_London --security-groups allow_all
aws ec2 run-instances --region eu-west-1 --image-id ami-ac9fb1df --count 1 --instance-type c4.large --key-name pdcc_Ireland --security-groups allow_all
aws ec2 run-instances --region ap-northeast-2 --image-id ami-815e88ef --count 1 --instance-type c4.large --key-name pdcc_Seoul --security-groups allow_all
aws ec2 run-instances --region ap-northeast-1 --image-id ami-099eee6e --count 1 --instance-type c4.large --key-name pdcc_Tokyo --security-groups allow_all
aws ec2 run-instances --region sa-east-1 --image-id ami-e72eb58b --count 1 --instance-type c4.large --key-name pdcc_SaoPaulo --security-groups allow_all
aws ec2 run-instances --region ca-central-1 --image-id ami-d21caeb6 --count 1 --instance-type c4.large --key-name pdcc_Central --security-groups allow_all
aws ec2 run-instances --region ap-southeast-1 --image-id ami-15892176 --count 1 --instance-type c4.large --key-name pdcc --security-groups allow_all
aws ec2 run-instances --region ap-southeast-2 --image-id ami-fd080d9e --count 1 --instance-type c4.large --key-name pdcc_Sydney --security-groups allow_all
aws ec2 run-instances --region eu-central-1 --image-id ami-ec905d83 --count 1 --instance-type c4.large --key-name pdcc_Frankfurt --security-groups allow_all
aws ec2 run-instances --region us-east-1 --image-id ami-1d05e00b --count 1 --instance-type c4.large --key-name pdcc_Virginia --security-groups allow_all
aws ec2 run-instances --region us-east-2 --image-id ami-d0e4beb5 --count 1 --instance-type c4.large --key-name pdcc_Ohio --security-groups allow_all
aws ec2 run-instances --region us-west-1 --image-id ami-2ea3f34e --count 1 --instance-type c4.large --key-name pdcc_California --security-groups allow_all
aws ec2 run-instances --region us-west-2 --image-id ami-fcdd6e9c --count 1 --instance-type c4.large --key-name pdcc_Oregon --security-groups allow_all
